## Contetnts
- 기초 연산
- 그룹 연산 : 집계, 변환, 필터링, 그룹매핑
- 함수 매핑 : map, apply, applymap
- Pivot

#### 기본 연산


In [20]:
import pandas as pd
import numpy as np
st1 = pd.Series({'국어':100,'영어':80,'수학':90})
st2 = pd.Series({'수학':80,'국어':90,'영어':80})

print(st1,'\n')
print(st2)

국어    100
영어     80
수학     90
dtype: int64 

수학    80
국어    90
영어    80
dtype: int64


In [21]:
pd.DataFrame(st1+st2)

0
국어  190
수학  170
영어  160

In [22]:
# 두 학생의 과목별 점수로 사칙연산 수행
add = st1 + st2
sub = st1 - st2
mul = st1 * st2
div = round((st1 / st2),2)
df = pd.concat([add,sub,mul,div],axis=1)
print(df)

      0   1     2     3
국어  190  10  9000  1.11
수학  170  10  7200  1.12
영어  160   0  6400  1.00


In [23]:
df = pd.concat([add,sub,mul,div],axis=1)
df.columns = ['덧셈','뺄셈','곱셈','나눗셈']
# df.index.name = '과목'
df

덧셈  뺄셈    곱셈   나눗셈
국어  190  10  9000  1.11
수학  170  10  7200  1.12
영어  160   0  6400  1.00

In [12]:
print(add,type(add))

국어    190
수학    170
영어    160
dtype: int64 <class 'pandas.core.series.Series'>


In [24]:
result = pd.DataFrame([add,sub,mul,div])
result

국어       수학      영어
0   190.00   170.00   160.0
1    10.00    10.00     0.0
2  9000.00  7200.00  6400.0
3     1.11     1.12     1.0

In [28]:
result = pd.DataFrame([add,sub,mul,div],index=['덧셈','뺄셈','곱셈','나눗셈'])
result

국어       수학      영어
덧셈    190.00   170.00   160.0
뺄셈     10.00    10.00     0.0
곱셈   9000.00  7200.00  6400.0
나눗셈     1.11     1.12     1.0

In [14]:
st1 = pd.Series({'국어':np.nan,'영어':80,'수학':90})
st2 = pd.Series({'수학':80,'국어':90})

add = st1 + st2
sub = st1 - st2
mul = st1 * st2
div = round((st1 / st2),2)

result = pd.DataFrame([add,sub,mul,div],
                     index=['덧셈','뺄셈','곱셈','나눗셈'])
result

국어       수학  영어
덧셈  NaN   170.00 NaN
뺄셈  NaN    10.00 NaN
곱셈  NaN  7200.00 NaN
나눗셈 NaN     1.12 NaN

In [ ]:
li = list('abcd')
li

['a', 'b', 'c', 'd']

In [31]:
df1 = pd.DataFrame(np.arange(12.).reshape((3,4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)), columns=list('abcde'))

df2.loc[1,'b'] = np.nan
print(df1)
print(df2)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [ ]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [ ]:
# 연산메소드(add(), sub(), mul(), div())와 fill_value()
# Q. df2의 NaN 값을 0으로 대체 후 사칙연산을 수행하세요.

In [ ]:
add_data = df1.add(df2,fill_value=0)
sub_data = df1.sub(df2, fill_value=0)
mul_data = df1.mul(df2, fill_value=0)
div_data = df1.div(df2, fill_value=0)
print(add_data,'\n')
print(sub_data,'\n')
print(mul_data,'\n')
print(div_data,'\n')

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0 

      a     b     c     d     e
0   0.0   0.0   0.0   0.0  -4.0
1  -1.0   5.0  -1.0  -1.0  -9.0
2  -2.0  -2.0  -2.0  -2.0 -14.0
3 -15.0 -16.0 -17.0 -18.0 -19.0 

      a     b      c      d    e
0   0.0   1.0    4.0    9.0  0.0
1  20.0   0.0   42.0   56.0  0.0
2  80.0  99.0  120.0  143.0  0.0
3   0.0   0.0    0.0    0.0  0.0 

     a         b         c         d    e
0  NaN  1.000000  1.000000  1.000000  0.0
1  0.8       inf  0.857143  0.875000  0.0
2  0.8  0.818182  0.833333  0.846154  0.0
3  0.0  0.000000  0.000000  0.000000  0.0 



In [32]:
print(df1,'\n')
print(1/df1)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0 

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909


In [33]:
# 계산인자를 뒤집어 계산
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [34]:
print(df1)
df1.rsub(1)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


a    b    c     d
0  1.0  0.0 -1.0  -2.0
1 -3.0 -4.0 -5.0  -6.0
2 -7.0 -8.0 -9.0 -10.0

In [35]:
print(df1)
df1.radd(1)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


a     b     c     d
0  1.0   2.0   3.0   4.0
1  5.0   6.0   7.0   8.0
2  9.0  10.0  11.0  12.0

In [36]:
print(df1)
df1.rmul(10)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0


a     b      c      d
0   0.0  10.0   20.0   30.0
1  40.0  50.0   60.0   70.0
2  80.0  90.0  100.0  110.0

In [37]:
# reindex할 때도 fill_value 지정
df1.reindex(columns=df2.columns,fill_value=0)


a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [ ]:
# 배열의 연산
arr = np.arange(12.).reshape(3,4)
print(arr,'\n')
print(arr[0])

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] 

[0. 1. 2. 3.]


In [ ]:
# broadcasting
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [38]:
# DataFrame과 Series간 연산
frame = pd.DataFrame(np.arange(12.).reshape(4,3),columns=list('bde'),
                    index = ['Utah','Ohio','Texas','Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [42]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [39]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [40]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [48]:
series2 = pd.Series(range(3),index=list('bef'))
series2

b    0
e    1
f    2
dtype: int64

In [47]:
print(frame,'\n')
frame + series2

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0 



b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [49]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [ ]:
print(frame,'\n')
frame.sub(series3,axis='index')

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0 



b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [ ]:
frame.sub(series3,axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [ ]:
a = np.arange(6).reshape(1,6)
a

array([[0, 1, 2, 3, 4, 5]])

In [ ]:
a = np.arange(6).reshape(6,)
a

array([0, 1, 2, 3, 4, 5])

#### 그룹 연산
* 복잡한 데이터를 어떤 기준에 따라 여러 그룹으로 나누어서 관찰할 수 있으며 이런 방식으로 분할 처리하는 것을 그룹 연산이라 함
* 그룹 연산은 데이터를 집계, 변환, 필터링하는데 효율적이며 판다스 groupby() 메소드를 사용함
* 그룹 객체 만들기(분할)
* 그룹 연산 메소드(적용-결합)

In [14]:
import pandas as pd
import seaborn as sns

# titanic 데이터셋에서 age, sex 등 5개 열을 선택하여 데이터프레임 만들기
titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','sex', 'class', 'fare', 'survived']]

print('승객 수:', len(df))
print(df.head())

승객 수: 891
    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
1  38.0  female  First  71.2833         1
2  26.0  female  Third   7.9250         1
3  35.0  female  First  53.1000         1
4  35.0    male  Third   8.0500         0


In [8]:
# class 열을 기준으로 분할(1개 열을 기준)
df1 = df[['age','fare','survived','class']]
grouped = df.groupby(['class'])
print(grouped)
# list(grouped)

In [7]:
# 그룹 객체를 iteration으로 출력: head() 메소드로 첫 5행만을 출력
for key, group in grouped:
    print('* key :', key)
    print('* number :', len(group))
    print(group.head())

* key : ('First',)
* number : 216
     age     fare  survived  class
1   38.0  71.2833         1  First
3   35.0  53.1000         1  First
6   54.0  51.8625         0  First
11  58.0  26.5500         1  First
23  28.0  35.5000         1  First
* key : ('Second',)
* number : 184
     age     fare  survived   class
9   14.0  30.0708         1  Second
15  55.0  16.0000         1  Second
17   NaN  13.0000         1  Second
20  35.0  26.0000         0  Second
21  34.0  13.0000         1  Second
* key : ('Third',)
* number : 491
    age     fare  survived  class
0  22.0   7.2500         0  Third
2  26.0   7.9250         1  Third
4  35.0   8.0500         0  Third
5   NaN   8.4583         0  Third
7   2.0  21.0750         0  Third


In [9]:
# 연산 메소드 적용
average = grouped.mean()
print(average)

              age       fare  survived
class                                 
First   38.233441  84.154687  0.629630
Second  29.877630  20.662183  0.472826
Third   25.140620  13.675550  0.242363


In [10]:
stat = grouped.max()
stat

age      fare  survived
class                           
First   80.0  512.3292         1
Second  70.0   73.5000         1
Third   74.0   69.5500         1

In [11]:
# 개별 그룹 선택하기
group3 = grouped.get_group('Third')
print(group3.head())

    age     fare  survived  class
0  22.0   7.2500         0  Third
2  26.0   7.9250         1  Third
4  35.0   8.0500         0  Third
5   NaN   8.4583         0  Third
7   2.0  21.0750         0  Third


In [12]:
group3.describe()

age        fare    survived
count  355.000000  491.000000  491.000000
mean    25.140620   13.675550    0.242363
std     12.495398   11.778142    0.428949
min      0.420000    0.000000    0.000000
25%     18.000000    7.750000    0.000000
50%     24.000000    8.050000    0.000000
75%     32.000000   15.500000    0.000000
max     74.000000   69.550000    1.000000

In [15]:
# class 열, sex 열을 기준으로 분할(여러 열을 기준으로 분할)
df2 = df[['age','fare','survived','class','sex']]
grouped_two = df2.groupby(['class', 'sex'])

In [16]:
# grouped_two 그룹 객체를 iteration으로 출력
for key, group in grouped_two:
    print('* key :', key)
    print('* number :', len(group))
    print(group.head())

* key : ('First', 'female')
* number : 94
     age      fare  survived  class     sex
1   38.0   71.2833         1  First  female
3   35.0   53.1000         1  First  female
11  58.0   26.5500         1  First  female
31   NaN  146.5208         1  First  female
52  49.0   76.7292         1  First  female
* key : ('First', 'male')
* number : 122
     age      fare  survived  class   sex
6   54.0   51.8625         0  First  male
23  28.0   35.5000         1  First  male
27  19.0  263.0000         0  First  male
30  40.0   27.7208         0  First  male
34  28.0   82.1708         0  First  male
* key : ('Second', 'female')
* number : 76
     age     fare  survived   class     sex
9   14.0  30.0708         1  Second  female
15  55.0  16.0000         1  Second  female
41  27.0  21.0000         0  Second  female
43   3.0  41.5792         1  Second  female
53  29.0  26.0000         1  Second  female
* key : ('Second', 'male')
* number : 108
     age  fare  survived   class   sex
17   NaN  13.

In [17]:
# grouped_two 그룹 객체에 연산 메소드 적용
average_two = grouped_two.mean()
print(average_two)

                     age        fare  survived
class  sex                                    
First  female  34.611765  106.125798  0.968085
       male    41.281386   67.226127  0.368852
Second female  28.722973   21.970121  0.921053
       male    30.740707   19.741782  0.157407
Third  female  21.750000   16.118810  0.500000
       male    26.507589   12.661633  0.135447


In [18]:
print(type(average_two))

# grouped_two 그룹 객체에서 개별 그룹 선택하기
group3f = grouped_two.get_group(('Third','female'))
print(group3f.head())

<class 'pandas.core.frame.DataFrame'>
     age     fare  survived  class     sex
2   26.0   7.9250         1  Third  female
8   27.0  11.1333         1  Third  female
10   4.0  16.7000         1  Third  female
14  14.0   7.8542         0  Third  female
18  31.0  18.0000         0  Third  female


데이터 집계(agg),
- 집계 연산을 처리하는 사용자 정의 함수를 그룹 객체에 적용하려면 agg() 메서드 사용
- 모든열에 여러 함수를 매핑 : group객체.agg([함수1,함수2,함수3,…])
- 각 열마다 다른 함수를 매핑 : group객체.agg({‘열1’: 함수1, ‘열2’:함수2, …})

변환(transform)
- 원소의 본래 행 인덱스와 열 이름을 기준으로 연산 결과를 반환
- 데이터 변환 연산 : group객체.transform(매핑함수)

필터링(filter)
- 그룹 객체에 filter() 메서드를 적용할 때 조건식을 가진 함수를 전달하면 조건이 참인 그룹만을 남김
- 그룹 객체 필터링 : group 객체.filter(조건 함수식)

객체에 함수 매핑(apply)
 - 판다스 객체의 개별 원소를 특정 함수에 일대일로 매핑. 사용자가 원하는 대부분의 연산을 그룹 객체에 적용
 - group 객체.apply(매핑함수)

https://kongdols-room.tistory.com/166

In [21]:
import pandas as pd
import seaborn as sns

# titanic 데이터셋에서 age, sex 등 5개 열을 선택하여 데이터프레임 만들기
titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','class', 'fare', 'survived']]

# class 열을 기준으로 분할
grouped = df.groupby(['class'])

In [22]:
mean_all = grouped.mean()
print(mean_all)
print()
print(type(mean_all))

              age       fare  survived
class                                 
First   38.233441  84.154687  0.629630
Second  29.877630  20.662183  0.472826
Third   25.140620  13.675550  0.242363

<class 'pandas.core.frame.DataFrame'>


In [23]:
# 각 그룹에 대한 모든 열의 표준편차를 집계하여 데이터프레임으로 반환
std_all = grouped.std()
print(std_all)
print()
print(type(std_all))

              age       fare  survived
class                                 
First   14.802856  78.380373  0.484026
Second  14.001077  13.417399  0.500623
Third   12.495398  11.778142  0.428949

<class 'pandas.core.frame.DataFrame'>


In [24]:
# 각 그룹에 대한 fare 열의 표준편차를 집계하여 시리즈로 반환
std_fare = grouped.fare.std()
print(std_fare)
print()
print(type(std_fare))

class
First     78.380373
Second    13.417399
Third     11.778142
Name: fare, dtype: float64

<class 'pandas.core.series.Series'>


In [25]:
# 그룹 객체에 agg() 메소드 적용 - 사용자 정의 함수를 인수로 전달
def min_max(x):    # 최대값 - 최소값
    return x.max() - x.min()

# 각 그룹의 최대값과 최소값의 차이를 계산하여 그룹별로 집계
agg_minmax = grouped.agg(min_max)
print(agg_minmax.head())

          age      fare  survived
class                            
First   79.08  512.3292         1
Second  69.33   73.5000         1
Third   73.58   69.5500         1


In [26]:
# 모든열에 여러 함수를 매핑 : group객체.agg([함수1,함수2,함수3,…])
# 각 열마다 다른 함수를 매핑 : group객체.agg({‘열1’: 함수1, ‘열2’:함수2, …})

agg_all = grouped.agg(['min', 'max'])
print(agg_all.head())

         age       fare           survived    
         min   max  min       max      min max
class                                         
First   0.92  80.0  0.0  512.3292        0   1
Second  0.67  70.0  0.0   73.5000        0   1
Third   0.42  74.0  0.0   69.5500        0   1


In [27]:
# 각 열마다 다른 함수를 적용하여 집계
agg_sep = grouped.agg({'fare':['min', 'max'], 'age':'mean'})
print(agg_sep.head())

       fare                  age
        min       max       mean
class                           
First   0.0  512.3292  38.233441
Second  0.0   73.5000  29.877630
Third   0.0   69.5500  25.140620


In [28]:
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset('titanic')
df = titanic.loc[:, ['age','sex', 'class', 'fare', 'survived']]

# class 열을 기준으로 분할
grouped = df.groupby(['class'])

# 데이터 개수가 200개 이상인 그룹만을 필터링하여 데이터프레임으로 반환
grouped_filter = grouped.filter(lambda x: len(x) >= 200)
print(grouped_filter.head())
print()
print(type(grouped_filter))

    age     sex  class     fare  survived
0  22.0    male  Third   7.2500         0
1  38.0  female  First  71.2833         1
2  26.0  female  Third   7.9250         1
3  35.0  female  First  53.1000         1
4  35.0    male  Third   8.0500         0

<class 'pandas.core.frame.DataFrame'>


In [29]:
grouped_filter.value_counts('class')

class
Third     491
First     216
Second      0
Name: count, dtype: int64

In [30]:
# age 열의 평균이 30보다 작은 그룹만을 필터링하여 데이터프레임으로 반환
age_filter = grouped.filter(lambda x: x.age.mean() < 30)
print(age_filter.tail())
print()
print(type(age_filter))

      age     sex   class    fare  survived
884  25.0    male   Third   7.050         0
885  39.0  female   Third  29.125         0
886  27.0    male  Second  13.000         0
888   NaN  female   Third  23.450         0
890  32.0    male   Third   7.750         0

<class 'pandas.core.frame.DataFrame'>


In [31]:
age_filter.value_counts('class')

class
Third     491
Second    184
First       0
Name: count, dtype: int64

In [36]:
list(grouped)

[(('First',),
        age     sex  class     fare  survived
  1    38.0  female  First  71.2833         1
  3    35.0  female  First  53.1000         1
  6    54.0    male  First  51.8625         0
  11   58.0  female  First  26.5500         1
  23   28.0    male  First  35.5000         1
  ..    ...     ...    ...      ...       ...
  871  47.0  female  First  52.5542         1
  872  33.0    male  First   5.0000         0
  879  56.0  female  First  83.1583         1
  887  19.0  female  First  30.0000         1
  889  26.0    male  First  30.0000         1
  
  [216 rows x 5 columns]),
 (('Second',),
        age     sex   class     fare  survived
  9    14.0  female  Second  30.0708         1
  15   55.0  female  Second  16.0000         1
  17    NaN    male  Second  13.0000         1
  20   35.0    male  Second  26.0000         0
  21   34.0    male  Second  13.0000         1
  ..    ...     ...     ...      ...       ...
  866  27.0  female  Second  13.8583         1
  874  28.0  

In [37]:
# 집계 : 각 그룹별 요약 통계정보를 집계
agg_grouped = grouped.apply(lambda x: x.describe())
print(agg_grouped)

                     age        fare    survived
class                                           
First  count  186.000000  216.000000  216.000000
       mean    38.233441   84.154687    0.629630
       std     14.802856   78.380373    0.484026
       min      0.920000    0.000000    0.000000
       25%     27.000000   30.923950    0.000000
       50%     37.000000   60.287500    1.000000
       75%     49.000000   93.500000    1.000000
       max     80.000000  512.329200    1.000000
Second count  173.000000  184.000000  184.000000
       mean    29.877630   20.662183    0.472826
       std     14.001077   13.417399    0.500623
       min      0.670000    0.000000    0.000000
       25%     23.000000   13.000000    0.000000
       50%     29.000000   14.250000    0.000000
       75%     36.000000   26.000000    1.000000
       max     70.000000   73.500000    1.000000
Third  count  355.000000  491.000000  491.000000
       mean    25.140620   13.675550    0.242363
       std     12.49

#### 함수 매핑
커스텀 함수(custom function)를 DataFrame에 적용하려면 map함수, apply함수, applymap함수를 사용
- map 함수는 Series의 각 요소에 함수를 적용.
- apply 함수는 Series 또는 DataFrame의 행이나 열에 함수를 적용.
- applymap 함수는 DataFrame의 각 요소에 함수를 적용.

In [52]:
import pandas as pd

# 예제 Series 생성
s = pd.Series([1, 2, 3, 4, 5])

# 각 요소에 2를 더하는 함수
s_mapped = s.map(lambda x: x + 2)
print(s_mapped)

0    3
1    4
2    5
3    6
4    7
dtype: int64


In [53]:
# Series에 적용 : Series 생성
s = pd.Series([1, 2, 3, 4, 5])

# 각 요소에 2를 더하는 함수
s_applied = s.apply(lambda x: x + 2)
print(s_applied)

0    3
1    4
2    5
3    6
4    7
dtype: int64


In [54]:
# DataFrame에 적용
# 예제 DataFrame 생성
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})

# 각 열에 대해 최대값을 구하는 함수
df_applied_col = df.apply(lambda x: x.max(), axis=0)
print(df_applied_col)

# 각 행에 대해 합계를 구하는 함수
df_applied_row = df.apply(lambda x: x.sum(), axis=1)
print(df_applied_row)


A    3
B    6
C    9
dtype: int64
0    12
1    15
2    18
dtype: int64


In [55]:
# applymap 함수는 DataFrame에만 적용되며, 각 요소에 함수를 적용
# 예제 DataFrame 생성
df = pd.DataFrame({
    'A': [1, 2, 3],
    'B': [4, 5, 6],
    'C': [7, 8, 9]
})

# 각 요소에 2를 더하는 함수
df_applymapped = df.applymap(lambda x: x + 2)
print(df_applymapped)


   A  B   C
0  3  6   9
1  4  7  10
2  5  8  11


In [56]:
# 함수 적용과 매핑
frame = pd.DataFrame(np.random.randn(4,3),columns=list('bde'),
                    index = ['Utah','Ohio','Texas','Oregon'])
frame

b         d         e
Utah    3.470711  0.497813 -0.381497
Ohio    0.657923 -0.497218 -0.513268
Texas  -0.949335 -1.459323  1.058245
Oregon -0.696942 -0.281582  1.325100

In [64]:
format = lambda x: '%.2f' %x

In [65]:
# map함수는 series에만 적용
frame['e'].map(format)

Utah      -0.38
Ohio      -0.51
Texas      1.06
Oregon     1.33
Name: e, dtype: object

In [58]:
# series의 최대값과 최소값의 차이를 계산
f = lambda x: x.max() - x.min()
frame.apply(f)

b    4.420046
d    1.957136
e    1.838368
dtype: float64

In [59]:
# 각 로우에 대해서 한 번씩 수행
frame.apply(f,axis='columns')

Utah      3.852208
Ohio      1.171191
Texas     2.517568
Oregon    2.022042
dtype: float64

In [60]:
f1 = lambda x: round(x*10)
frame.apply(f1,axis=0)

b     d     e
Utah    35.0   5.0  -4.0
Ohio     7.0  -5.0  -5.0
Texas   -9.0 -15.0  11.0
Oregon  -7.0  -3.0  13.0

In [62]:
frame

b         d         e
Utah    3.470711  0.497813 -0.381497
Ohio    0.657923 -0.497218 -0.513268
Texas  -0.949335 -1.459323  1.058245
Oregon -0.696942 -0.281582  1.325100

In [61]:
f1 = lambda x: round(x*20)
frame.apply(f1,axis=1)

b     d     e
Utah    69.0  10.0  -8.0
Ohio    13.0 -10.0 -10.0
Texas  -19.0 -29.0  21.0
Oregon -14.0  -6.0  27.0

In [ ]:
f1 = lambda x: sum(x)
frame.apply(f1,axis=0)

b   -1.139104
d    1.845122
e    4.089626
dtype: float64

In [ ]:
# 여러값을 가진 Series 반환
print(frame,'\n')
def f(x):
    return pd.Series([x.min(),x.max()], index=['min','max'])
frame.apply(f)

               b         d         e
Utah   -2.155876  0.588667 -0.986228
Ohio   -1.003634  0.103495 -0.443402
Texas   0.709309  0.331136  0.775696
Oregon -0.998970  0.415681  1.601540 



b         d         e
min -2.155876  0.103495 -0.986228
max  0.709309  0.588667  1.601540

In [ ]:
# 실수값을 문자열 포맷으로 변환
format = lambda x: '%.2f' %x
frame.applymap(format)

b      d     e
Utah    -0.76   0.17  0.32
Ohio    -0.30   1.97  0.68
Texas    0.22   0.81  0.72
Oregon  -0.31  -1.10  2.37

In [40]:
data = np.random.randint(1,100,size=(5,5))
df = pd.DataFrame(data, columns=list('abcde'))
df

a   b   c   d   e
0  33  77  72  18  35
1  34  75  65  68  75
2  83  55   9  56   3
3  92   1  57  76  84
4  34   3  68  38  23

In [41]:
df['f'] = df.apply(lambda x:x.a+x.b+x.c+x.d+x.e,axis=1)
df

a   b   c   d   e    f
0  33  77  72  18  35  235
1  34  75  65  68  75  317
2  83  55   9  56   3  206
3  92   1  57  76  84  310
4  34   3  68  38  23  166

In [42]:
def z_score(x):
    return (x - x.mean()) / x.std()

In [43]:
# 원소의 본래 행 인덱스와 열 이름을 기준으로 연산 결과를 반환
df_zscore = df.a.transform(z_score)
df_zscore

0   -0.748489
1   -0.714774
2    0.937298
3    1.240739
4   -0.714774
Name: a, dtype: float64

In [44]:
df_zscore = df.apply(lambda x:z_score(x))
df_zscore

a         b         c         d         e         f
0 -0.748489  0.923106  0.688342 -1.416683 -0.260787 -0.179662
1 -0.714774  0.870054  0.417646  0.716876  0.898268  1.068839
2  0.937298  0.339533 -1.747925  0.204822 -1.188032 -0.621205
3  1.240739 -1.092873  0.108279  1.058245  1.159055  0.962259
4 -0.714774 -1.039821  0.533658 -0.563260 -0.608504 -1.230230

####Pivot
pivot 함수의 구성 형식
- index: 새로운 DataFrame에서 인덱스로 사용할 기존 열 또는 열들의 이름.
- columns: 새로운 DataFrame에서 열로 사용할 기존 열 또는 열들의 이름.
- values: 피벗할 때 사용할 값이 있는 열의 이름.

기능
- 긴 형식의 데이터를 넓은 형식으로 변환하여 특정 차원에서 데이터를 재구성.
- 피벗된 데이터를 통해 시간 경과에 따른 변화나 여러 카테고리의 비교를 쉽게 할 수 있다.
- 넓은 형식의 데이터는 시각화 도구에서 더 쉽게 다룰 수 있다.

In [45]:
# 날짜(date)를 인덱스로, 도시(city)를 열로, 온도(temperature)를 값으로 사용하여 피벗 테이블을 생성
import pandas as pd

# 예제 DataFrame 생성
data = {
    'date': ['2021-01-01', '2021-01-01', '2021-01-02', '2021-01-02'],
    'city': ['New York', 'Los Angeles', 'New York', 'Los Angeles'],
    'temperature': [32, 75, 30, 78]
}
df = pd.DataFrame(data)

# 피벗 테이블 생성
pivot_df = df.pivot(index='date', columns='city', values='temperature')
print(pivot_df)


city        Los Angeles  New York
date                             
2021-01-01           75        32
2021-01-02           78        30


In [46]:
# 중복된 값을 평균으로 처리하여 피벗 테이블을 생성
data = {
    'date': ['2021-01-01', '2021-01-01', '2021-01-01', '2021-01-02', '2021-01-02'],
    'city': ['New York', 'Los Angeles', 'New York', 'New York', 'Los Angeles'],
    'temperature': [32, 75, 30, 30, 78]
}
df = pd.DataFrame(data)

# 피벗 테이블 생성 (중복 값의 평균 계산)
pivot_table_df = df.pivot_table(index='date', columns='city', values='temperature', aggfunc='mean')
print(pivot_table_df)


city        Los Angeles  New York
date                             
2021-01-01           75        31
2021-01-02           78        30


In [47]:
# 다중 인덱스와 다중 값 사용 : 날짜와 도시를 기준으로 온도와 습도를 모두 포함한 피벗 테이블을 생성
data = {
    'date': ['2021-01-01', '2021-01-01', '2021-01-02', '2021-01-02'],
    'city': ['New York', 'Los Angeles', 'New York', 'Los Angeles'],
    'temperature': [32, 75, 30, 78],
    'humidity': [80, 20, 85, 15]
}
df = pd.DataFrame(data)

# 다중 인덱스 및 다중 값 피벗 테이블 생성
pivot_multi_df = df.pivot(index='date', columns='city')
print(pivot_multi_df)


           temperature             humidity         
city       Los Angeles New York Los Angeles New York
date                                                
2021-01-01          75       32          20       80
2021-01-02          78       30          15       85



Q. 데이터를 아래와 같이 수정한 후 연도별 판매금액 증감여부에 따라서 고객을 구매금액의 증가, 감소를 기준으로 1,0으로 구분하는 파생변수를 생성하세요.

[데이터 수정 사항]

상품별 가격대 결정 : 1 ~ 5번 상품 평균가격을 1000 ~ 50000원으로 산정(1000, 5000, 10000, 25000, 50000 )  
판매 수량 성장율: 저가(1000, 5000) 20%, 중가(10000,25000) -10%, 고가(50000) 5% 성장
상품 비중(판매금액 기준) : 저가 50%, 중가 30%, 고가 20%  
고객 비중도 상품 비중과 동일  
판매금액 변수 생성 (a_19, a_20) : 판매수량 * 평균가격

In [ ]:
import numpy as np
import pandas as pd

id = np.arange(1,1001)
i1 = pd.Series(id)
gender = np.random.randint(2,size=1000)
g1 = pd.Series(gender)
age = np.random.randint(1,81,size=1000)
a1 = pd.Series(age)
region = np.random.randint(1,11,size=1000)
r1 = pd.Series(region)
pdt_19 = np.random.randint(1, 6,size=1000)
p_19 = pd.Series(pdt_19)
pdt_20 = np.random.randint(1, 6,size=1000)
p_20 = pd.Series(pdt_20)
price_avg_19 = np.random.rand(1000)
pr19 = price_avg_19*10000
pa_19 = pd.Series(pr19)
price_avg_20 = np.random.rand(1000)
pr20 = price_avg_20*10000
pa_20 = pd.Series(pr20)
qty_19 = np.random.randint(1,101, 1000)
q_19 = pd.Series(qty_19)
qty_20 = np.random.randint(1,101, 1000)
q_20 = pd.Series(qty_20)
time_19 = np.random.randint(1, 24, 1000)
t_19 = pd.Series(time_19)
time_20 = np.random.randint(1, 24, 1000)
t_20 = pd.Series(time_20)
df = pd.concat([i1, g1,a1,r1,p_19,p_20,pa_19,pa_20,q_19,q_20,t_19,t_20],axis=1)
df.rename(columns={0:'id',1:'gender',2:'age',3:'region',4:'pdt_19',5:'pdt_20',6:'pa_19',7:'pa_20',\
                  8:'q_19',9:'q_20',10:'t_19',11:'t_20'},inplace=True)
df['pa_19'] = round(df['pa_19'],2)
df['pa_20'] = round(df['pa_20'],2)
df.iloc[0,1] = np.nan
print(type(pa_19))
df.head()

<class 'pandas.core.series.Series'>


id  gender  age  region  pdt_19  pdt_20    pa_19    pa_20  q_19  q_20  \
0   1     NaN    5       6       2       3  7514.94  7190.14    68    14   
1   2     0.0   35       6       3       2  5775.01  3210.76    67    97   
2   3     0.0   58       4       5       1   793.22  5219.88    96    31   
3   4     0.0   34      10       3       5  5860.92  7517.87    50    44   
4   5     0.0   22       1       3       1  6050.41  4050.06    84    91   

   t_19  t_20  
0     1     7  
1    12    11  
2    23    17  
3    12    18  
4    13     3